### PR TITLE
Add performFailproof

### PR DESCRIPTION
**Pull request by jvoigtlaender**
@rtfeldman, as discussed elsewhere.

For the documentation snippet, I have based this on the documentation as given at http://package.elm-lang.org/packages/elm-lang/core/4.0.1/Task#perform.

### CODE REVIEW

**Comment by rtfeldman** [comment]
Cool!

Two thoughts:
1. I don't think adding a dependency on Basics.Extra is warranted for a trivial one-line function. I think  code duplication (with maybe a link to the Basics.Extra docs) is better here.
2. How do you feel about `performFailproof` as a name?

**Comment by jvoigtlaender** [comment]
Both fine with me. Will revise accordingly.

**Comment by jvoigtlaender** [comment]
Revised and squashed commits.

**Comment by rtfeldman** [comment]
Great, thanks!

**Comment by rtfeldman** [comment]
Published as 2.0.0

**Pull request merged**
